version: '3.8'
services:
  nginx:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      web:
        condition: service_started

  web:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=pass@321
      - DB_NAME=student_enrollment
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'pass@321'
      MYSQL_DATABASE: student_enrollment
      MYSQL_ROOT_HOST: '%'    # allow root from other containers; or create a non-root user instead
      # Optionally create an app user:
      # MYSQL_USER: 'app'
      # MYSQL_PASSWORD: 'app_pass'
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db_data:
